In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [2]:
a=pd.read_csv("creditcard.csv")
a.head(10)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0
5,2.0,-0.425966,0.960523,1.141109,-0.168252,0.420987,-0.029728,0.476201,0.260314,-0.568671,...,-0.208254,-0.559825,-0.026398,-0.371427,-0.232794,0.105915,0.253844,0.081080,3.67,0
6,4.0,1.229658,0.141004,0.045371,1.202613,0.191881,0.272708,-0.005159,0.081213,0.464960,...,-0.167716,-0.270710,-0.154104,-0.780055,0.750137,-0.257237,0.034507,0.005168,4.99,0
7,7.0,-0.644269,1.417964,1.074380,-0.492199,0.948934,0.428118,1.120631,-3.807864,0.615375,...,1.943465,-1.015455,0.057504,-0.649709,-0.415267,-0.051634,-1.206921,-1.085339,40.80,0
8,7.0,-0.894286,0.286157,-0.113192,-0.271526,2.669599,3.721818,0.370145,0.851084,-0.392048,...,-0.073425,-0.268092,-0.204233,1.011592,0.373205,-0.384157,0.011747,0.142404,93.20,0
9,9.0,-0.338262,1.119593,1.044367,-0.222187,0.499361,-0.246761,0.651583,0.069539,-0.736727,...,-0.246914,-0.633753,-0.120794,-0.385050,-0.069733,0.094199,0.246219,0.083076,3.68,0

In [9]:
a.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [7]:
a.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [16]:
a['Class'].value_counts()

0    284315
1       492
Name: Class, dtype: int64

In [18]:
# this data is very unblanced
# 0 this is normal transaction
# 1 this is fraudulent transaction

In [19]:
#seprating data for analysis
legit=a[a.Class==0]
fraud=a[a.Class==1]

In [21]:
legit.shape

(284315, 31)

In [22]:
#statistical measures of data
legit.Amount.describe()

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [23]:
fraud.Amount.describe()

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [24]:
#campare the values for both transaction
a.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94838.202258,0.008258,-0.006271,0.012171,-0.007860,0.005453,0.002419,0.009637,-0.000987,0.004467,...,-0.000644,-0.001235,-0.000024,0.000070,0.000182,-0.000072,-0.000089,-0.000295,-0.000131,88.291022
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

In [25]:
# under-sampling
# Build a sample dataset containing similar distribution of normal transaction and fraudulent transcation
# number of fraudlent transaction -->492

In [26]:
legit_Sample=legit.sample(n=492) #random data select

In [27]:
#containing two datafram

In [30]:
new_data=pd.concat([legit_Sample, fraud], axis=0)

In [31]:
new_data.head(10)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
211202,138308.0,2.103812,-0.720162,-1.746744,-0.375408,-0.177213,-0.765531,-0.033192,-0.254633,-0.799588,...,-0.349010,-0.462827,0.091708,-0.396360,0.028536,0.567259,-0.083295,-0.081649,39.94,0
262372,160442.0,-6.317904,-3.588560,0.534568,5.800331,2.140578,-0.569840,-2.164967,0.396747,-1.477281,...,-0.614665,-0.871182,-3.821436,-0.037904,-0.953392,0.082759,0.358490,-1.737964,25.03,0
135971,81489.0,1.046309,-0.309020,1.211101,0.650261,-0.654227,0.967213,-0.874374,0.492807,0.648249,...,0.018656,0.280276,0.076083,-0.235622,0.079133,0.357654,0.046390,0.011021,11.50,0
98524,66696.0,-0.649032,1.014173,0.607374,-0.549446,1.524229,0.628817,1.037960,0.255079,-0.790988,...,-0.006816,-0.155259,-0.646880,-1.757278,0.904413,-0.244333,0.008185,0.016953,1.00,0
168411,119215.0,-0.215225,0.928313,-0.323512,-0.963821,1.092612,-1.263482,1.280830,-0.290278,0.066804,...,0.134861,0.615053,-0.160628,-0.164055,-0.588291,0.275641,0.174539,0.258657,19.99,0
167389,118654.0,1.549328,-2.158800,-2.812841,-2.953363,0.227639,0.658788,0.006301,0.051544,0.577417,...,0.024600,0.133369,-0.198873,-0.940771,0.098966,-0.649923,0.014455,-0.025098,319.98,0
231123,146620.0,-2.171167,0.942179,-1.951841,0.316346,-4.774156,5.274410,-2.748875,-11.898840,-2.015679,...,-4.509666,1.806426,-3.364458,0.527166,0.633967,0.646939,1.091486,-0.087522,1122.16,0
244577,152408.0,2.059147,-0.961738,-1.937373,-0.908867,-0.133916,-0.705946,-0.091335,-0.222837,-0.734218,...,0.304242,0.727738,-0.030434,0.744273,0.276810,-0.052035,-0.082794,-0.069041,84.85,0
29342,35427.0,-1.363550,0.095058,-0.682814,1.420259,-1.367614,0.358557,2.036980,0.447228,-1.002140,...,0.424247,0.305767,1.213575,-0.001728,-0.011273,-0.323701,0.044539,0.105987,535.50,0
102091,68049.0,-2.788099,-1.939619,0.280088,-0.331202,1.823827,-2.159319,-0.364837,0.472595,-0.875622,...,0.082325,-1.132236,0.184985,0.024100,-0.436214,0.485242,-0.110148,-0.373093,83.00,0

In [33]:
new_data['Class'].value_counts()

0    492
1    492
Name: Class, dtype: int64

In [34]:
new_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,98944.532520,-0.108885,-0.028333,-0.045719,0.048424,0.147198,-0.039708,-0.013405,-0.012533,-0.000033,...,0.016811,-0.007962,-0.009228,-0.033143,-0.016851,-0.014674,-0.008615,-0.041880,-0.015098,93.000386
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

In [37]:
x=new_data.drop(columns='Class', axis=1)
y=new_data['Class']

In [38]:
x

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
211202,138308.0,2.103812,-0.720162,-1.746744,-0.375408,-0.177213,-0.765531,-0.033192,-0.254633,-0.799588,...,-0.607377,-0.349010,-0.462827,0.091708,-0.396360,0.028536,0.567259,-0.083295,-0.081649,39.94
262372,160442.0,-6.317904,-3.588560,0.534568,5.800331,2.140578,-0.569840,-2.164967,0.396747,-1.477281,...,-1.763720,-0.614665,-0.871182,-3.821436,-0.037904,-0.953392,0.082759,0.358490,-1.737964,25.03
135971,81489.0,1.046309,-0.309020,1.211101,0.650261,-0.654227,0.967213,-0.874374,0.492807,0.648249,...,-0.142150,0.018656,0.280276,0.076083,-0.235622,0.079133,0.357654,0.046390,0.011021,11.50
98524,66696.0,-0.649032,1.014173,0.607374,-0.549446,1.524229,0.628817,1.037960,0.255079,-0.790988,...,-0.243447,-0.006816,-0.155259,-0.646880,-1.757278,0.904413,-0.244333,0.008185,0.016953,1.00
168411,119215.0,-0.215225,0.928313,-0.323512,-0.963821,1.092612,-1.263482,1.280830,-0.290278,0.066804,...,-0.177418,0.134861,0.615053,-0.160628,-0.164055,-0.588291,0.275641,0.174539,0.258657,19.99
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279863,169142.0,-1.927883,1.125653,-4.518331,1.749293,-1.566487,-2.010494,-0.882850,0.697211,-2.064945,...,1.252967,0.778584,-0.319189,0.639419,-0.294885,0.537503,0.788395,0.292680,0.147968,390.00
280143,169347.0,1.378559,1.289381,-5.004247,1.411850,0.442581,-1.326536,-1.413170,0.248525,-1.127396,...,0.226138,0.370612,0.028234,-0.145640,-0.081049,0.521875,0.739467,0.389152,0.186637,0.76
280149,169351.0,-0.676143,1.126366,-2.213700,0.468308,-1.120541,-0.003346,-2.234739,1.210158,-0.652250,...,0.247968,0.751826,0.834108,0.190944,0.032070,-0.739695,0.471111,0.385107,0.194361,77.89
281144,169966.0,-3.113832,0.585864,-5.399730,1.817092,-0.840618,-2.943548,-2.208002,1.058733,-1.632333,...,0.306271,0.583276,-0.269209,-0.456108,-0.183659,-0.328168,0.606116,0.884876,-0.253700,245.00
281674,170348.0,1.991976,0.158476,-2.583441,0.408670,1.151147,-0.096695,0.223050,-0.068384,0.577829,...,-0.017652,-0.164350,-0.295135,-0.072173,-0.450261,0.313267,-0.289617,0.002988,-0.015309,42.53

In [39]:
y

211202    0
262372    0
135971    0
98524     0
168411    0
         ..
279863    1
280143    1
280149    1
281144    1
281674    1
Name: Class, Length: 984, dtype: int64

In [43]:
X_test, X_train, Y_test, Y_train= train_test_split(x,y,test_size=0.2, stratify=y, random_state=2)

In [45]:
print(x.shape, X_train.shape, X_test.shape)

(984, 30) (197, 30) (787, 30)

In [46]:
#Model Traning
#logistic Regression
model=LogisticRegression()
model.fit(X_train, Y_train)

LogisticRegression()

In [48]:
X_train_predict=model.predict(X_train)
train_data_acc=accuracy_score(X_train_predict, Y_train)

In [49]:
train_data_acc

0.9593908629441624

In [50]:
X_test_predict=model.predict(X_test)
test_data_acc=accuracy_score(X_test_predict, Y_test)